name: client
description: WebSocket client SDK for the Tinest daemon.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  http: ^1.6.0
  json_rpc_2: ^4.1.0
  path: ^1.9.1
  protocol: ^0.1.0
  relay_protocol: ^0.1.0
  stream_channel: ^2.1.4
  web_socket_channel: ^3.0.3

dev_dependencies:
  async: ^2.13.1
  test: ^1.31.1
