import 'package:daemon/src/features/plugins/runtime/plugin_json_schema.dart';
import 'package:protocol/protocol.dart';

/// A plugin registration returned invalid data from its effect-free `define`
/// handler.
final class PluginRegistrationException extends FormatException {
  /// Creates a registration validation failure.
  const new(super.message, {this.path});

  /// Stable field path within the registration document.
  final String? path;
}

/// Lifecycle transitions that an extension plugin may observe.
enum PluginLifecycle {
  /// An Agent definition became attached to a session.
  agentAttach('agent_attach'),

  /// An Agent definition was detached from a session.
  agentDetach('agent_detach'),

  /// A session was opened.
  sessionOpen('session_open'),

  /// A session is about to close.
  sessionClose('session_close'),

  /// A user turn is about to begin.
  beforeTurn('before_turn'),

  /// A model request is about to begin.
  beforeModel('before_model'),

  /// A model request finished.
  afterModel('after_model'),

  /// A tool invocation is about to begin.
  beforeTool('before_tool'),

  /// A tool invocation finished.
  afterTool('after_tool'),

  /// A turn finished.
  afterTurn('after_turn'),

  /// The owning operation was cancelled.
  cancel('cancel'),

  /// A lifecycle transition failed.
  error('error'),

  /// A durable scheduled handler became due.
  scheduled('scheduled'),

  /// The user activated a declarative UI action.
  uiAction('ui_action');

  new(this.wireName);

  /// Stable Lua registration key.
  final String wireName;
}

/// SDK-owned kinds of executable contribution binding.
enum PluginHandlerKind {
  /// Agent driver callback.
  driver('driver'),

  /// Model-visible tool callback.
  tool('tool'),

  /// Revision-bound callback used by dynamically materialized tools.
  toolTemplate('tool_template'),

  /// Lifecycle callback.
  hook('hook'),

  /// Session-control normalization callback.
  sessionControl('session_control'),

  /// Declarative UI renderer callback.
  ui('ui'),

  /// Declarative UI action callback.
  action('action');

  new(this.wireName);

  /// Stable SDK wire name.
  final String wireName;
}

/// Revision-local opaque identity of a Lua closure exported by the SDK.
///
/// Plugin authors never provide [internalKey]. It is accepted only when it is
/// the deterministic key for the contribution kind, lifecycle, and local ID.
final class PluginHandlerBinding {
  /// Creates one already-validated internal handler binding.
  const new({
    required this.pluginId,
    required this.executionRevisionHash,
    required this.kind,
    required this.localId,
    required this.internalKey,
    this.lifecycle,
  });

  /// Plugin revision that created this binding.
  final String pluginId;

  /// Exact composite execution revision that created this binding.
  final String executionRevisionHash;

  /// Contribution kind owning the closure.
  final PluginHandlerKind kind;

  /// Plugin-local contribution ID.
  final String localId;

  /// Runtime-only named-handler key generated by the SDK.
  final String internalKey;

  /// Lifecycle encoded into hook and action keys.
  final PluginLifecycle? lifecycle;

  @override
  String toString() => internalKey;
}

/// One registered Agent driver.
final class PluginDriverRegistration {
  /// Creates validated driver metadata.
  const new({
    required this.id,
    required this.binding,
    required this.requiredCapabilities,
    required this.declaredOperations,
    required this.requiredModelCapabilities,
    required this.metadata,
  });

  /// Globally qualified contribution ID.
  final String id;

  /// SDK-owned closure binding.
  final PluginHandlerBinding binding;

  /// Host capabilities needed by this driver.
  final Set<String> requiredCapabilities;

  /// Exact SDK primitive operations referenced by this contribution's `uses`.
  final Set<String> declaredOperations;

  /// Provider-neutral model features required by the harness.
  final Set<String> requiredModelCapabilities;

  /// JSON presentation or driver-specific metadata.
  final Map<String, Object?> metadata;
}

/// One independently selectable Lua tool contribution.
final class PluginToolRegistration {
  /// Creates validated tool metadata.
  const new({
    required this.id,
    required this.name,
    required this.description,
    required this.binding,
    required this.kind,
    required this.inputSchema,
    required this.outputSchema,
    required this.payloadSchema,
    required this.effects,
    required this.requiredCapabilities,
    required this.declaredOperations,
    required this.presentation,
  });

  /// Globally qualified contribution ID.
  final String id;

  /// Exact model-visible wire name. Human labels belong in [presentation].
  final String name;

  /// Human-readable behavior summary.
  final String description;

  /// SDK-owned closure binding.
  final PluginHandlerBinding binding;

  /// `function`, `deferred`, or non-visible `template`.
  final String kind;

  /// Provider-neutral JSON input schema.
  final Map<String, Object?> inputSchema;

  /// Optional provider-neutral JSON output schema.
  final Map<String, Object?>? outputSchema;

  /// Validated cross-VM payload schema for a dynamic template.
  final Map<String, Object?>? payloadSchema;

  /// Declared effects. The capability broker may raise their effective risk.
  final Set<String> effects;

  /// Host capabilities needed by this tool.
  final Set<String> requiredCapabilities;

  /// Exact SDK primitive operations referenced by this contribution's `uses`.
  final Set<String> declaredOperations;

  /// Declarative presentation metadata.
  final Map<String, Object?> presentation;
}

/// One ordered lifecycle handler contribution.
final class PluginHookRegistration {
  /// Creates validated lifecycle hook metadata.
  const new({
    required this.id,
    required this.lifecycle,
    required this.binding,
    required this.requiredCapabilities,
    required this.declaredOperations,
    required this.payloadSchema,
    required this.metadata,
  });

  /// Globally qualified contribution ID.
  final String id;

  /// Transition observed by this hook.
  final PluginLifecycle lifecycle;

  /// SDK-owned closure binding.
  final PluginHandlerBinding binding;

  /// Host capabilities needed by this hook.
  final Set<String> requiredCapabilities;

  /// Exact SDK primitive operations referenced by this contribution's `uses`.
  final Set<String> declaredOperations;

  /// Validated callback payload for a UI action or scheduled handler.
  ///
  /// Ordinary lifecycle hooks receive their lifecycle context and leave this
  /// unset. Action refs and durable scheduled handlers receive only data
  /// matching this schema.
  final Map<String, Object?>? payloadSchema;

  /// JSON metadata passed to the driver.
  final Map<String, Object?> metadata;
}

/// One composer or session control contribution.
final class PluginSessionControlRegistration {
  /// Creates validated control metadata.
  const new({
    required this.id,
    required this.binding,
    required this.requiredCapabilities,
    required this.declaredOperations,
    required this.schema,
    required this.metadata,
  });

  /// Globally qualified contribution ID.
  final String id;

  /// SDK-owned closure binding.
  final PluginHandlerBinding binding;

  /// Host capabilities needed by this control.
  final Set<String> requiredCapabilities;

  /// Exact SDK primitive operations referenced by this contribution's `uses`.
  final Set<String> declaredOperations;

  /// JSON schema for the control value.
  final Map<String, Object?> schema;

  /// Declarative presentation metadata.
  final Map<String, Object?> metadata;
}

/// One declarative native UI contribution.
final class PluginUiRegistration {
  /// Creates validated UI contribution metadata.
  const new({
    required this.id,
    required this.slot,
    required this.binding,
    required this.requiredCapabilities,
    required this.declaredOperations,
    required this.inputSchema,
    required this.metadata,
    this.dependsOn = const <String>{},
  });

  /// Globally qualified contribution ID.
  final String id;

  /// Host-owned surface receiving the document.
  final PluginUiSlot slot;

  /// Live host state this surface reads, from [pluginUiDependencies].
  ///
  /// A declarative surface is rendered on demand, so a panel over changing
  /// host state goes stale the moment that state moves. Declaring the
  /// dependency lets the host render the surface again when it does, instead
  /// of leaving the last answer up until something else happens to reload it.
  final Set<String> dependsOn;

  /// SDK-owned closure binding.
  final PluginHandlerBinding binding;

  /// Host capabilities needed while rendering or handling actions.
  final Set<String> requiredCapabilities;

  /// Exact SDK primitive operations referenced by this contribution's `uses`.
  final Set<String> declaredOperations;

  /// JSON schema for the value passed directly to the render callback.
  final Map<String, Object?> inputSchema;

  /// Declarative presentation metadata.
  final Map<String, Object?> metadata;
}

/// Fully validated registration for one immutable plugin revision.
final class PluginRegistration {
  /// Creates an immutable registration.
  new({
    required this.descriptor,
    required this.revisionHash,
    required this.driver,
    required List<PluginToolRegistration> tools,
    required List<PluginToolRegistration> templates,
    required List<PluginHookRegistration> hooks,
    required List<PluginSessionControlRegistration> sessionControls,
    required List<PluginUiRegistration> ui,
  }) : tools = List<PluginToolRegistration>.unmodifiable(tools),
       templates = List<PluginToolRegistration>.unmodifiable(templates),
       hooks = List<PluginHookRegistration>.unmodifiable(hooks),
       sessionControls = List<PluginSessionControlRegistration>.unmodifiable(
         sessionControls,
       ),
       ui = List<PluginUiRegistration>.unmodifiable(ui);

  /// Descriptor enriched with runtime contribution metadata.
  final PluginDescriptorDto descriptor;

  /// Composite execution revision pin used for the bound closure invocation.
  final String revisionHash;

  /// Optional driver contribution. An Agent still requires exactly one driver.
  final PluginDriverRegistration? driver;

  /// Independently selectable tools.
  final List<PluginToolRegistration> tools;

  /// Plugin-internal dynamic tool templates, never model-visible or selectable.
  final List<PluginToolRegistration> templates;

  /// Ordered lifecycle hooks owned by this plugin.
  final List<PluginHookRegistration> hooks;

  /// Agent-selected composer and session controls.
  final List<PluginSessionControlRegistration> sessionControls;

  /// Declarative host-rendered surfaces.
  final List<PluginUiRegistration> ui;
}

/// Converts the JSON-compatible value returned by Lua into typed metadata.
abstract final class PluginRegistrationParser {
  /// Validates one revision registration.
  static PluginRegistration parse({
    required PluginDescriptorDto descriptor,
    required String revisionHash,
    required Object? value,
  }) {
    final envelope = _object(value, r'$');
    if (envelope['api'] != 5) {
      throw const PluginRegistrationException(
        'Plugin registration must use API 5.',
        path: r'$.api',
      );
    }
    final spec = _object(envelope['spec'], r'$.spec');
    final declared = descriptor.requestedCapabilities.toSet();
    final contributions = <PluginContributionDto>[];
    final ids = <String>{};

    PluginDriverRegistration? driver;
    if (spec['driver'] != null) {
      final raw = _object(spec['driver'], r'$.driver');
      final localId = _string(raw['id'], r'$.driver.id');
      final id = _contributionId(descriptor.id, localId, ids, r'$.driver.id');
      final capabilities = _capabilities(
        raw['required_capabilities'],
        r'$.driver.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        r'$.driver.declared_operations',
      );
      final metadata = _optionalObject(raw['metadata'], r'$.driver.metadata');
      driver = PluginDriverRegistration(
        id: id,
        binding: _binding(
          raw['binding'],
          r'$.driver.binding',
          PluginHandlerKind.driver,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
        ),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        requiredModelCapabilities: _stringSet(
          raw['required_model_capabilities'],
          r'$.driver.required_model_capabilities',
          _modelCapabilityPattern,
        ),
        metadata: metadata,
      );
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.driver,
          requiredCapabilities: capabilities.toList(growable: false),
          metadata: <String, dynamic>{
            'bindingId': driver.binding.localId,
            'declaredOperations': operations.toList(growable: false),
            'requiredModelCapabilities': driver.requiredModelCapabilities
                .toList(growable: false),
            ...metadata,
          },
        ),
      );
    }

    final tools = <PluginToolRegistration>[];
    final templates = <PluginToolRegistration>[];
    final rawTools = <({String path, Map<String, Object?> raw, bool template})>[
      for (final indexed in _objects(spec['tools'], r'$.tools').indexed)
        (
          path:
              r'$.tools['
              '${indexed.$1}]',
          raw: indexed.$2,
          template: false,
        ),
      for (final indexed in _objects(spec['templates'], r'$.templates').indexed)
        (
          path:
              r'$.templates['
              '${indexed.$1}]',
          raw: indexed.$2,
          template: true,
        ),
    ];
    for (final entry in rawTools) {
      final path = entry.path;
      final raw = entry.raw;
      final localId = _string(raw['id'], '$path.id');
      final id = _contributionId(descriptor.id, localId, ids, '$path.id');
      final kind = entry.template
          ? 'template'
          : _string(raw['kind'] ?? 'function', '$path.kind');
      if (!const <String>{'function', 'deferred', 'template'}.contains(kind)) {
        throw PluginRegistrationException(
          'Unsupported tool kind: $kind',
          path: '$path.kind',
        );
      }
      final inputSchema = _schema(raw['input_schema'], '$path.input_schema');
      if (inputSchema['type'] != 'object') {
        throw PluginRegistrationException(
          'Tool input schemas must have type object.',
          path: '$path.input_schema.type',
        );
      }
      final capabilities = _capabilities(
        raw['required_capabilities'],
        '$path.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        '$path.declared_operations',
      );
      final tool = PluginToolRegistration(
        id: id,
        name: _string(raw['name'] ?? raw['id'], '$path.name'),
        description: _string(
          raw['description'] ?? raw['name'] ?? raw['id'],
          '$path.description',
        ),
        binding: _binding(
          raw['binding'],
          '$path.binding',
          entry.template
              ? PluginHandlerKind.toolTemplate
              : PluginHandlerKind.tool,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
        ),
        kind: kind,
        inputSchema: inputSchema,
        outputSchema: raw['output_schema'] == null
            ? null
            : _schema(raw['output_schema'], '$path.output_schema'),
        payloadSchema: entry.template
            ? _schema(raw['payload_schema'], '$path.payload_schema')
            : null,
        effects: _stringSet(raw['effects'], '$path.effects', _effectPattern),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        presentation: _resolveReferences(
          _optionalObject(raw['presentation'], '$path.presentation'),
          descriptor.id,
          '$path.presentation',
        ),
      );
      (entry.template ? templates : tools).add(tool);
      if (entry.template) continue;
      final presentation = Map<String, dynamic>.from(tool.presentation);
      final descriptorTool = AgentToolDefinitionDto(
        id: id,
        originPluginId: descriptor.id,
        contributionId: localId,
        name: tool.name,
        description: tool.description,
        risk: _riskForEffects(tool.effects),
        group: presentation['group'] is String
            ? presentation['group']! as String
            : descriptor.id,
        kind: AgentToolKind.values.byName(tool.kind),
        inputSchema: Map<String, dynamic>.from(tool.inputSchema),
        outputSchema: tool.outputSchema == null
            ? null
            : Map<String, dynamic>.from(tool.outputSchema!),
        effects: tool.effects.toList(growable: false),
        presentation: presentation,
      );
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.tool,
          requiredCapabilities: capabilities.toList(growable: false),
          tool: descriptorTool,
          metadata: <String, dynamic>{
            'bindingId': tool.binding.localId,
            'declaredOperations': operations.toList(growable: false),
          },
        ),
      );
    }

    final hooks = <PluginHookRegistration>[];
    final rawHooks = _optionalObject(spec['hooks'], r'$.hooks');
    for (final lifecycle in PluginLifecycle.values) {
      final rawValue = rawHooks[lifecycle.wireName];
      if (rawValue == null) continue;
      final raw = _object(
        rawValue,
        r'$.hooks.'
        '${lifecycle.wireName}',
      );
      final path =
          r'$.hooks.'
          '${lifecycle.wireName}';
      final localId = _string(
        raw['id'] ?? lifecycle.wireName.replaceAll('_', '-'),
        '$path.id',
      );
      final id = _contributionId(descriptor.id, localId, ids, '$path.id');
      final capabilities = _capabilities(
        raw['required_capabilities'],
        '$path.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        '$path.declared_operations',
      );
      final metadata = _optionalObject(raw['metadata'], '$path.metadata');
      final payloadSchema =
          lifecycle == PluginLifecycle.scheduled &&
              raw['payload_schema'] != null
          ? _schema(raw['payload_schema'], '$path.payload_schema')
          : null;
      final hook = PluginHookRegistration(
        id: id,
        lifecycle: lifecycle,
        binding: _binding(
          raw['binding'],
          '$path.binding',
          PluginHandlerKind.hook,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
          lifecycle: lifecycle,
        ),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        payloadSchema: payloadSchema,
        metadata: metadata,
      );
      hooks.add(hook);
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.extension,
          requiredCapabilities: capabilities.toList(growable: false),
          metadata: <String, dynamic>{
            'lifecycle': lifecycle.wireName,
            'bindingId': hook.binding.localId,
            'declaredOperations': operations.toList(growable: false),
            'payloadSchema': ?payloadSchema,
            ...metadata,
          },
        ),
      );
    }
    final unknownHooks = rawHooks.keys.toSet().difference(
      PluginLifecycle.values.map((value) => value.wireName).toSet(),
    );
    if (unknownHooks.isNotEmpty) {
      throw PluginRegistrationException(
        'Unsupported lifecycle hook: ${unknownHooks.first}',
        path:
            r'$.hooks.'
            '${unknownHooks.first}',
      );
    }

    for (final indexed in _objects(
      spec['ui_actions'],
      r'$.ui_actions',
    ).indexed) {
      final path =
          r'$.ui_actions['
          '${indexed.$1}]';
      final raw = indexed.$2;
      final localId = _string(raw['id'], '$path.id');
      final id = _contributionId(descriptor.id, localId, ids, '$path.id');
      final capabilities = _capabilities(
        raw['required_capabilities'],
        '$path.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        '$path.declared_operations',
      );
      final payloadSchema = _schema(
        raw['payload_schema'],
        '$path.payload_schema',
      );
      final metadata = <String, Object?>{
        ..._optionalObject(raw['metadata'], '$path.metadata'),
        'uiAction': true,
      };
      final action = PluginHookRegistration(
        id: id,
        lifecycle: PluginLifecycle.uiAction,
        binding: _binding(
          raw['binding'],
          '$path.binding',
          PluginHandlerKind.action,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
          lifecycle: PluginLifecycle.uiAction,
        ),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        payloadSchema: payloadSchema,
        metadata: metadata,
      );
      hooks.add(action);
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.extension,
          requiredCapabilities: capabilities.toList(growable: false),
          metadata: <String, dynamic>{
            'lifecycle': PluginLifecycle.uiAction.wireName,
            'bindingId': action.binding.localId,
            'uiAction': true,
            'declaredOperations': operations.toList(growable: false),
            'payloadSchema': payloadSchema,
            ...metadata,
          },
        ),
      );
    }

    final controls = <PluginSessionControlRegistration>[];
    for (final indexed in _objects(
      spec['session_controls'],
      r'$.session_controls',
    ).indexed) {
      final path =
          r'$.session_controls['
          '${indexed.$1}]';
      final raw = indexed.$2;
      final localId = _string(raw['id'], '$path.id');
      final id = _contributionId(descriptor.id, localId, ids, '$path.id');
      final capabilities = _capabilities(
        raw['required_capabilities'],
        '$path.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        '$path.declared_operations',
      );
      final schema = raw['schema'] == null
          ? throw PluginRegistrationException(
              'Session controls require a JSON schema.',
              path: '$path.schema',
            )
          : _schema(raw['schema'], '$path.schema');
      final rawMetadata = _optionalObject(raw['metadata'], '$path.metadata');
      if (!rawMetadata.containsKey('default')) {
        throw PluginRegistrationException(
          'Session controls require a default value.',
          path: '$path.metadata.default',
        );
      }
      late final Object? defaultValue;
      try {
        defaultValue = normalizePluginJson(
          rawMetadata['default'],
          path: '$path.metadata.default',
        );
        validatePluginJsonSchema(
          schema,
          defaultValue,
          path: '$path.metadata.default',
        );
      } on PluginJsonValidationException catch (error) {
        throw PluginRegistrationException(error.message, path: error.path);
      }
      final metadata = Map<String, Object?>.unmodifiable(<String, Object?>{
        ...rawMetadata,
        'default': defaultValue,
      });
      final control = PluginSessionControlRegistration(
        id: id,
        binding: _binding(
          raw['binding'],
          '$path.binding',
          PluginHandlerKind.sessionControl,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
        ),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        schema: schema,
        metadata: metadata,
      );
      controls.add(control);
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.sessionControl,
          requiredCapabilities: capabilities.toList(growable: false),
          metadata: <String, dynamic>{
            'bindingId': control.binding.localId,
            'declaredOperations': operations.toList(growable: false),
            'schema': control.schema,
            ...metadata,
          },
        ),
      );
    }

    final ui = <PluginUiRegistration>[];
    for (final indexed in _objects(spec['ui'], r'$.ui').indexed) {
      final path =
          r'$.ui['
          '${indexed.$1}]';
      final raw = indexed.$2;
      final localId = _string(raw['id'], '$path.id');
      final id = _contributionId(descriptor.id, localId, ids, '$path.id');
      final slotName = _string(raw['slot'], '$path.slot');
      final slot = _uiSlot(slotName, '$path.slot');
      final capabilities = _capabilities(
        raw['required_capabilities'],
        '$path.required_capabilities',
        declared,
      );
      final operations = _operations(
        raw['declared_operations'],
        '$path.declared_operations',
      );
      final inputSchema = _schema(raw['input_schema'], '$path.input_schema');
      final metadata = _optionalObject(raw['metadata'], '$path.metadata');
      final dependsOn = _uiDependencies(raw['depends_on'], '$path.depends_on');
      final contribution = PluginUiRegistration(
        id: id,
        slot: slot,
        binding: _binding(
          raw['binding'],
          '$path.binding',
          PluginHandlerKind.ui,
          localId,
          pluginId: descriptor.id,
          executionRevisionHash: revisionHash,
        ),
        requiredCapabilities: capabilities,
        declaredOperations: operations,
        inputSchema: inputSchema,
        metadata: metadata,
        dependsOn: dependsOn,
      );
      ui.add(contribution);
      contributions.add(
        PluginContributionDto(
          pluginId: descriptor.id,
          id: id,
          kind: PluginContributionKind.ui,
          requiredCapabilities: capabilities.toList(growable: false),
          metadata: <String, dynamic>{
            'slots': <String>[slot.name],
            'bindingId': contribution.binding.localId,
            'declaredOperations': operations.toList(growable: false),
            'inputSchema': inputSchema,
            if (dependsOn.isNotEmpty)
              'dependsOn': dependsOn.toList(growable: false),
            ...metadata,
          },
        ),
      );
    }

    return PluginRegistration(
      descriptor: descriptor.copyWith(contributions: contributions),
      revisionHash: revisionHash,
      driver: driver,
      tools: tools,
      templates: templates,
      hooks: hooks,
      sessionControls: controls,
      ui: ui,
    );
  }
}

ToolRisk _riskForEffects(Set<String> effects) {
  if (effects.any(
    (effect) =>
        effect.startsWith('network.') ||
        effect.startsWith('secret.') ||
        effect == 'mcp.invoke' ||
        effect.endsWith('.dangerous'),
  )) {
    return ToolRisk.dangerous;
  }
  if (effects.any(
    (effect) => effect.startsWith('process.') || effect.contains('command'),
  )) {
    return ToolRisk.command;
  }
  if (effects.any(
    (effect) =>
        effect.contains('write') ||
        effect.contains('patch') ||
        effect.contains('delete') ||
        effect.contains('spawn') ||
        effect.contains('interrupt'),
  )) {
    return ToolRisk.write;
  }
  return ToolRisk.read;
}

final RegExp _idPattern = RegExp(r'^[a-z][a-z0-9_-]*$');
final RegExp _capabilityPattern = RegExp(r'^[a-z][a-z0-9_.:-]*$');
final RegExp _modelCapabilityPattern = RegExp(r'^[a-z][a-z0-9_.:-]*$');
final RegExp _effectPattern = RegExp(r'^[a-z][a-z0-9_.:-]*$');
final RegExp _operationPattern = RegExp(
  r'^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+$',
);

Map<String, Object?> _object(Object? value, String path) {
  if (value is List<Object?> && value.isEmpty) return <String, Object?>{};
  if (value case final Map<Object?, Object?> map) {
    final result = <String, Object?>{};
    for (final entry in map.entries) {
      if (entry.key is! String) {
        throw PluginRegistrationException(
          'Object keys must be strings.',
          path: path,
        );
      }
      result[entry.key! as String] = entry.value;
    }
    return result;
  }
  throw PluginRegistrationException('Expected an object.', path: path);
}

Map<String, Object?> _optionalObject(Object? value, String path) =>
    value == null ? <String, Object?>{} : _object(value, path);

List<Map<String, Object?>> _objects(Object? value, String path) {
  if (value == null) return const <Map<String, Object?>>[];
  if (value is! List<Object?>) {
    throw PluginRegistrationException('Expected an array.', path: path);
  }
  return <Map<String, Object?>>[
    for (var index = 0; index < value.length; index += 1)
      _object(value[index], '$path[$index]'),
  ];
}

String _string(Object? value, String path) {
  if (value is String && value.trim().isNotEmpty) return value;
  throw PluginRegistrationException('Expected a non-empty string.', path: path);
}

PluginHandlerBinding _binding(
  Object? value,
  String path,
  PluginHandlerKind expectedKind,
  String expectedLocalId, {
  required String pluginId,
  required String executionRevisionHash,
  PluginLifecycle? lifecycle,
}) {
  final binding = _object(value, path);
  final kindName = _string(binding['kind'], '$path.kind');
  if (kindName != expectedKind.wireName) {
    throw PluginRegistrationException(
      'Binding kind must be ${expectedKind.wireName}.',
      path: '$path.kind',
    );
  }
  final localId = _string(binding['id'], '$path.id');
  if (localId != expectedLocalId) {
    throw PluginRegistrationException(
      'Binding ID must match its contribution ID.',
      path: '$path.id',
    );
  }
  final internalKey = _string(binding['key'], '$path.key');
  final expectedKey = lifecycle == null
      ? '__tinest.${expectedKind.wireName}.$expectedLocalId'
      : '__tinest.${expectedKind.wireName}.${lifecycle.wireName}.'
            '$expectedLocalId';
  if (internalKey != expectedKey) {
    throw PluginRegistrationException(
      'Binding key is not the deterministic SDK key.',
      path: '$path.key',
    );
  }
  if (binding.keys.toSet().difference(const <String>{
    'kind',
    'id',
    'key',
  }).isNotEmpty) {
    throw PluginRegistrationException(
      'Binding contains unsupported fields.',
      path: path,
    );
  }
  return PluginHandlerBinding(
    pluginId: pluginId,
    executionRevisionHash: executionRevisionHash,
    kind: expectedKind,
    localId: localId,
    internalKey: internalKey,
    lifecycle: lifecycle,
  );
}

Map<String, Object?> _resolveReferences(
  Map<String, Object?> value,
  String pluginId,
  String path,
) => Map<String, Object?>.unmodifiable(
  value.map(
    (key, item) =>
        MapEntry(key, _resolveReferenceValue(item, pluginId, '$path.$key')),
  ),
);

Object? _resolveReferenceValue(Object? value, String pluginId, String path) {
  if (value case final Map<Object?, Object?> map) {
    final object = _object(map, path);
    if (object.containsKey('__tinest_ref')) {
      final kind = _string(object['__tinest_ref'], '$path.__tinest_ref');
      if (kind != 'ui' && kind != 'action' && kind != 'tool') {
        throw PluginRegistrationException(
          'Unsupported metadata reference kind: $kind',
          path: '$path.__tinest_ref',
        );
      }
      if (object.keys.toSet().difference(const <String>{
        '__tinest_ref',
        'id',
      }).isNotEmpty) {
        throw PluginRegistrationException(
          'Metadata reference contains unsupported fields.',
          path: path,
        );
      }
      final id = _string(object['id'], '$path.id');
      if (!_idPattern.hasMatch(id)) {
        throw PluginRegistrationException(
          'Metadata reference must use a lowercase local ID.',
          path: '$path.id',
        );
      }
      return '$pluginId/$id';
    }
    return Map<String, Object?>.unmodifiable(
      object.map(
        (key, item) =>
            MapEntry(key, _resolveReferenceValue(item, pluginId, '$path.$key')),
      ),
    );
  }
  if (value is List<Object?>) {
    return List<Object?>.unmodifiable(<Object?>[
      for (var index = 0; index < value.length; index += 1)
        _resolveReferenceValue(value[index], pluginId, '$path[$index]'),
    ]);
  }
  return value;
}

String _contributionId(
  String pluginId,
  String localId,
  Set<String> ids,
  String path,
) {
  if (!_idPattern.hasMatch(localId)) {
    throw PluginRegistrationException(
      'Contribution IDs must be lowercase local IDs.',
      path: path,
    );
  }
  final id = '$pluginId/$localId';
  if (!ids.add(id)) {
    throw PluginRegistrationException(
      'Duplicate contribution ID: $id',
      path: path,
    );
  }
  return id;
}

Set<String> _capabilities(Object? value, String path, Set<String> declared) {
  final capabilities = _stringSet(value, path, _capabilityPattern);
  final undeclared = capabilities.difference(declared);
  if (undeclared.isNotEmpty) {
    throw PluginRegistrationException(
      'Contribution requires a capability absent from PLUGIN.md: '
      '${undeclared.first}',
      path: path,
    );
  }
  return capabilities;
}

Set<String> _operations(Object? value, String path) =>
    _stringSet(value, path, _operationPattern);

Set<String> _stringSet(Object? value, String path, RegExp pattern) {
  if (value == null) return const <String>{};
  if (value is! List<Object?>) {
    throw PluginRegistrationException('Expected an array.', path: path);
  }
  final result = <String>{};
  for (var index = 0; index < value.length; index += 1) {
    final item = _string(value[index], '$path[$index]');
    if (!pattern.hasMatch(item)) {
      throw PluginRegistrationException(
        'Invalid value: $item',
        path: '$path[$index]',
      );
    }
    if (!result.add(item)) {
      throw PluginRegistrationException(
        'Duplicate value: $item',
        path: '$path[$index]',
      );
    }
  }
  return Set<String>.unmodifiable(result);
}

Map<String, Object?> _schema(Object? value, String path) {
  final schema = _object(value, path);
  _validateJson(schema, path);
  final type = schema['type'];
  if (type != null && type is! String && type is! List<Object?>) {
    throw PluginRegistrationException(
      'Schema type must be a string or array.',
      path: '$path.type',
    );
  }
  return Map<String, Object?>.unmodifiable(schema);
}

void _validateJson(Object? value, String path) {
  switch (value) {
    case null || bool() || String():
      return;
    case final num number:
      if (number.isFinite) return;
      throw PluginRegistrationException(
        'Schema numbers must be finite.',
        path: path,
      );
    case final List<Object?> values:
      for (var index = 0; index < values.length; index += 1) {
        _validateJson(values[index], '$path[$index]');
      }
    case final Map<Object?, Object?> values:
      for (final entry in values.entries) {
        if (entry.key is! String) {
          throw PluginRegistrationException(
            'Schema object keys must be strings.',
            path: path,
          );
        }
        _validateJson(entry.value, '$path.${entry.key}');
      }
    default:
      throw PluginRegistrationException(
        'Schema contains a non-JSON value.',
        path: path,
      );
  }
}

PluginUiSlot _uiSlot(String value, String path) {
  for (final slot in PluginUiSlot.values) {
    if (slot.name == value) return slot;
  }
  throw PluginRegistrationException('Unsupported UI slot: $value', path: path);
}

/// Live host state a UI contribution may declare a dependency on.
///
/// Closed on purpose: each entry is state the host knows how to watch and
/// derive a revision from. An open set would let a plugin name something the
/// host cannot observe, which reads as a working declaration and silently
/// never invalidates anything.
const Set<String> pluginUiDependencies = <String>{'session_tree'};

Set<String> _uiDependencies(Object? value, String path) {
  if (value == null) return const <String>{};
  if (value is! List<Object?>) {
    throw PluginRegistrationException('Expected an array.', path: path);
  }
  final declared = <String>{};
  for (var index = 0; index < value.length; index += 1) {
    final name = _string(value[index], '$path[$index]');
    if (!pluginUiDependencies.contains(name)) {
      throw PluginRegistrationException(
        'Unsupported UI dependency: $name',
        path: '$path[$index]',
      );
    }
    if (!declared.add(name)) {
      throw PluginRegistrationException(
        'Duplicate value: $name',
        path: '$path[$index]',
      );
    }
  }
  return Set<String>.unmodifiable(declared);
}
