name: cli
description: Standalone command-line client for the Tinest daemon.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  client: ^0.1.0
  cliweave:
    git:
      url: https://github.com/tinyrack-net/dart-packages.git
      ref: 866a29af27a9f3e077b1dd905f2f79d7ca2c2769
      path: packages/cliweave
  daemon: ^0.1.0
  path: ^1.9.1
  protocol: ^0.1.0
  qr: ^3.0.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.31.1
