name: cli
description: Standalone command-line client for the Tinest daemon.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  client: ^0.1.0
  cliweave:
    git:
      url: https://github.com/tinyrack-net/dart-packages.git
      ref: 5da5311a53bc2cf401f4bc8efb97518adeeced32
      path: packages/cliweave
  daemon: ^0.1.0
  path: ^1.9.1
  protocol: ^0.1.0
  qr: ^4.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.31.1
