# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Tinyrack.Tinest
PackageVersion: __VERSION__
InstallerLocale: en-US
InstallerType: inno
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: __DOWNLOAD_ROOT__/Tinest-setup-win-x64.exe
    InstallerSha256: __INSTALLER_SHA256__
ManifestType: installer
ManifestVersion: 1.12.0
