name: relay
description: Opaque WebSocket relay server for Tinest.
version: 0.6.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  relay_protocol: ^0.1.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  cliweave:
    git:
      url: https://github.com/tinyrack-net/dart-packages.git
      ref: 866a29af27a9f3e077b1dd905f2f79d7ca2c2769
      path: packages/cliweave
  test: ^1.31.1
